services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_db"]
      interval: 1s
      retries: 3
    networks:
      - backend

  seeder:
    build:
      context: ./db_seeder
    container_name: seeder
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - backend

  web:
    build:
      context: ./web
    container_name: web
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      seeder:
        condition: service_completed_successfully
    env_file:
      - ./.env
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
